### ISSUE TITLE
Erreur dans les journaux

### ISSUE THREAD

**Issue by pinpspinps** [kamaradclimber/signal_ecogaz#6]
Bonjour,
J'ai remarqué aujourd’hui que l'intégration génère des erreurs dans les journaux de Home Assistant.

**1ère erreur**
```
Enregistreur: homeassistant.components.sensor
Source: helpers/entity_platform.py:356
intégration: Capteur (documentation, problèmes)
S'est produit pour la première fois: 08:41:06 (1 occurrences)
Dernier enregistrement: 08:41:06

Error while setting up signal_ecogaz platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/signal_ecogaz/__init__.py", line 223, in _find_ecogaz_level
    ecogaz_data = next(
                  ^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/signal_ecogaz/sensor.py", line 42, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/signal_ecogaz/__init__.py", line 176, in _handle_coordinator_update
    ecogaz_level = self._find_ecogaz_level()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/signal_ecogaz/__init__.py", line 231, in _find_ecogaz_level
    raise RuntimeError(
RuntimeError: Unable to find ecogaz level for 2024-06-09
```

**2ème erreur**
```
Cette erreur provient d'une intégration personnalisée

Enregistreur: homeassistant
Source: custom_components/signal_ecogaz/__init__.py:231
intégration: Signal Ecogaz (documentation, problèmes)
S'est produit pour la première fois: 08:51:06 (1 occurrences)
Dernier enregistrement: 08:51:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/signal_ecogaz/__init__.py", line 223, in _find_ecogaz_level
    ecogaz_data = next(
                  ^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/signal_ecogaz/__init__.py", line 176, in _handle_coordinator_update
    ecogaz_level = self._find_ecogaz_level()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/signal_ecogaz/__init__.py", line 231, in _find_ecogaz_level
    raise RuntimeError(
RuntimeError: Unable to find ecogaz level for 2024-06-09
```

Pouvez-vous m'aider avec ce problème?
Bonne journée

**Comment by kamaradclimber** [comment]
Effectivement j'ai eu le même problème sur mon installation ajourd'hui entre minuit et 11:15.
Le problème s'est ensuite résolu.

Il semble que le problème soit récurent: 
![image](https://github.com/kamaradclimber/signal_ecogaz/assets/503537/6efe2fac-bf33-4bce-ab99-bff0361ce39a)

Je pense que cela vient du moment où les données J+4 sont publiées.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/signal_ecogaz/releases/tag/0.2.5 devrait corriger le problème. Merci pour le rapport de bug
